name: GitHub Actions Demo
on: [push]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: check out repo code
        uses: actions/checkout@v3
      - run:   terraform init
      - run:  terraform plan
      - run: terraform apply -auto-approve
